version: '3.8'

services:
  flask_api:
    build: ./python-api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - ./python-api:/app
    command: "python app.py"
    networks:
      - app-network
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
      MYSQL_HOST: mysql_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  node_api:
    build: ./node-api
    container_name: node_api
    ports:
      - "3000:3000"
    volumes:
      - ./node-api:/usr/src/app
    environment:
      FLASK_API_URL: "http://flask_api:5000"
    networks:
      - app-network
    depends_on:
      - flask_api

networks:
  app-network:
    driver: bridge
